/* Legitimate legacy Amplified content, excluding compromised and theme-demo posts. */
window.AMP_CONTENT = {
  videos: [
    ['Documentary Film', 'Documentaries', 'WugcpUaCl-c'],
    ['TV Commercial', 'TV Commercials', 'RgKYjMejVDY'],
    ['Motion Graphics', 'Motion Graphics', 'JEotojhglDA'],
    ['Documentary Film', 'Documentaries', 'ut6aWaoh1Ls'],
    ['2D Animation', '2D Animation', 'akAUIM9SPd4'],
    ['TV Commercial', 'TV Commercials', 'GYHbInojBhY'],
    ['TV Commercial', 'TV Commercials', 'BHjXuue7VF4'],
    ['Documentary Film', 'Documentaries', 'nb8kNuO2z0o'],
    ['TV Commercial', 'TV Commercials', 'jUwd4jBk554'],
    ['2D Animation', '2D Animation', 'YD0YtTvrrqE'],
    ['TV Commercial', 'TV Commercials', 'JBaccAjLedU'],
    ['Animated Logo', 'Animated Logos', 'fxOMetxz2JA'],
    ['Animated Logo', 'Animated Logos', 'RZbBm38LMRI'],
    ['Animated Logo', 'Animated Logos', 'mPKr05SiV64'],
    ['TV Commercial', 'TV Commercials', 'Ru8DrnS__kc'],
    ['Documentary Film', 'Documentaries', 'WPpf2swFZnw'],
    ['3D Animation', '3D Animation', 'Dk4srw03ir8'],
    ['3D Animation', '3D Animation', 'EN0yXEqS4cw'],
    ['3D Animation', '3D Animation', 'f_Gvs7nSSEg'],
    ['Animated Logo', 'Animated Logos', '2qbEAdJyocc']
  ],
  audio: [
    ['Africana Good Food', 'Radio Commercial', 'https://anchor.fm/amplified-kreative/embed/episodes/Africana-Good-Food-e1ocrq0'],
    ['era92 Creative', 'Corporate Ring Back Tone', 'https://anchor.fm/amplified-kreative/embed/episodes/era92-Creative-e1oeg0l']
  ],
  images: [
    ['Humanitarian Platform', 'Branding', 'assets/legacy/portfolio/humanitarian-platform.jpg'],
    ['Legal Framework Report', 'Print', 'assets/legacy/portfolio/legal-framework-report.jpg'],
    ['Vehicle Branding', 'Print', 'assets/legacy/portfolio/back-car.jpg'],
    ['Branding & Graphic Design', 'Branding', 'assets/legacy/portfolio/left.jpg'],
    ['Logo Final', 'Branding', 'assets/legacy/portfolio/logo-final.jpg'],
    ['Logo Design', 'Branding', 'assets/legacy/portfolio/logo.jpg'],
    ['Logo Design 01', 'Branding', 'assets/legacy/portfolio/logo-1.jpg'],
    ['Logo Design 02', 'Branding', 'assets/legacy/portfolio/logo-2.jpg'],
    ['Logo Design 03', 'Branding', 'assets/legacy/portfolio/logo-3.jpg'],
    ['Logo Design 04', 'Branding', 'assets/legacy/portfolio/logo-4.jpg'],
    ['Fleet Branding', 'Print', 'assets/legacy/portfolio/main-car.jpg'],
    ['Social Media Campaign 01', 'Digital Marketing', 'assets/legacy/portfolio/social-media-1.jpg'],
    ['Social Media Campaign 02', 'Digital Marketing', 'assets/legacy/portfolio/social-media-2.jpg'],
    ['Social Media Campaign 03', 'Digital Marketing', 'assets/legacy/portfolio/social-media.jpg'],
    ['Logo Design 05', 'Branding', 'assets/legacy/portfolio/logo-2-alt.jpg'],
    ['Embossed Brand Identity', 'Branding', 'assets/legacy/portfolio/logo-embossed.jpg'],
    ['Branded Merchandise', 'Print', 'assets/legacy/portfolio/sweater-mockup.jpg'],
    ['Branding Gallery 01', 'Branding', 'assets/legacy/portfolio/image-1.jpg'],
    ['Branding Gallery 02', 'Branding', 'assets/legacy/portfolio/image-2.jpg'],
    ['Branding Gallery 03', 'Branding', 'assets/legacy/portfolio/image-3.jpg'],
    ['Branding Gallery 04', 'Branding', 'assets/legacy/portfolio/image-4.jpg'],
    ['Branding Gallery 05', 'Branding', 'assets/legacy/portfolio/image-5.jpg'],
    ['Branding Gallery 06', 'Branding', 'assets/legacy/portfolio/image-6.jpg'],
    ['Branding Gallery 08', 'Branding', 'assets/legacy/portfolio/image-8.jpg'],
    ['Branding Gallery 09', 'Branding', 'assets/legacy/portfolio/image-9.jpg'],
    ['NGO Forum', 'Branding', 'assets/portfolio/ngo-forum.jpeg']
  ],
  legacyRoutes: {
    '/portfolio/': 'work.html',
    '/branding-graphic-design/': 'service-branding.html',
    '/video-production/': 'service-video.html',
    '/website-design-development/': 'service-web.html',
    '/digital-marketing/': 'service-digital.html',
    '/audio-production/': 'service-audio.html',
    '/photography/': 'service-photography.html',
    '/printing-3/': 'service-printing.html',
    '/contact-us/': 'contact.html',
    '/our-story/': 'about.html',
    '/blog/': 'about.html'
  }
};
